### ISSUE TITLE
src/dist not copied into app

### ISSUE THREAD

**Issue by voxoid0** [crotwell/gradle-macappbundle#42]
The gradle application plugin copies src/dist files into the distribution/lib folder. It's be really super nice if macappbundle did the same. Then we can distribute to Windows and Mac with the same src file structure. For now I need to create my own task to run after createApp to do so.

**Comment by crotwell** [comment]
Seems like being compatible with the application plugin is a good idea, but from what I can tell from the gradle application and distribution plugin docs, it looks like the contents of src/main/dist would be copied into the top level of the distribution, so would appear directly in side the .dmg instead of in the lib folder. Also I am a little unclear as to why this would effect things in the lib folder? Am I misunderstanding?
