### ISSUE TITLE
Support code signing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crotwell/gradle-macappbundle#6]
```
Since this is so important now for OSX 10.8, it would be nice if this plugin 
supported it. We need to:

1. Rename JavaApplicationStub to the name of the .app
2. Take a key from the keystore and sign the app
```

Original issue reported on code.google.com by `aristede...@gmail.com` on 10 Sep 2012 at 6:20

**Comment by hepcat72** [comment]
I thought I would comment for those such as myself that want to take advantage of code-signing to simply eliminate the "Unknown Developer" error...

First, the value of "certIdentity", at a (unique) minimum can be the user ID from the .cer file that you download from your apple developer account.  Or it can be a number of other values from that .cer file, including a substring of the "Common Name" or even the 40 character SHA-1 string.  If the value doesn't uniquely identify the cert, you'll get an error about an ambiguous cert identity.

The .cer file is installed by double-clicking it, and if you obtained the .cer file from your own Apple Developer account, a paired "private key" will be created.  Without that key, the codesign will fail with "No identity found".

For educational institutions with an apple developer account such as mine, you must be an admin on the account or higher to download a cert.  And in order to distribute your app outside of the app store, you need a cert of type "Developer ID Application", which can only be created by the Team Agent.  And you as an admin, must download it from your own account.

I won't get into the details of how you obtain membership in the apple developer program account held by your organization, but I will say that unless you're a high-up at your university, with the ability to bind your university to legal agreements, you can't obtain a free educational institution apple developer account yourself, but your apple ID has to have its own free developer account and then be invited to your university's account with Apple as a team member.
