### ISSUE TITLE
Switch app launcher to one with a better JRE missing error?

### ISSUE THREAD

**Issue by hepcat72** [crotwell/gradle-macappbundle#61]
I was wondering if you'd be willing to swap out the standard oracle JavaAppLauncher strategy with one that yields a nicer error when the JRE is missing/inadequate.  I found someone who did this for their project:

https://github.com/Fedict/eid-viewer/commit/1d1a31f23a29fc8426be728c78aa9059092d3a5c

I don't trust my users will understand the vague "JRELoadError" if they missed the java requirement in the documentation and we would rather not bundle a separate JRE.

**Comment by crotwell** [comment]
Seems like a reasonable idea. I would probably make it optional, so have a new "appStyle" like
```
macAppBundle {
  appStyle = 'universalJavaApplicationStub'
}
```
or something similar. 

This would be a fairly big change, basically everywhere there is "Oracle" or "Apple" would have to have new code for this style.

Would you be able/interested in trying this and generating a pull request? I don't think I will have time to look at this anytime soon.

**Comment by airsquared** [comment]
@hepcat72 and @crotwell Is there any progress on this?

**Comment by hepcat72** [comment]
I haven’t adopted this. It was just a suggestion from my standpoint.

**Comment by crotwell** [comment]
Have not had time to look into this, so no progress. Happy to have a pull request if you are interested.

**Comment by airsquared** [comment]
@crotwell I'll try to implement this.

**Comment by airsquared** [comment]
@crotwell I have the code ready([link](https://github.com/crotwell/gradle-macappbundle/compare/master...airsquared:master)), but I'm unable to test it(I'm not sure what the problem is and I don't think that it has to do with the code itself).

I published it to my maven local repository and added it in my test project's `build.gradle` file, but I constantly get this error: `Could not find method macAppBundle() for arguments [build_6gz7env276lqlzhplu1kbq7kg$_run_closure6@3c770a6b] on root project 'test' of type org.gradle.api.Project.`. Do you by chance know how to fix this?

**Comment by airsquared** [comment]
Done: #66. Just implemented and tested it and it works for me.
